// Indian cities list
window.INDIAN_CITIES = [
    'Mumbai',
    'Delhi',
    'New Delhi',
    'Bengaluru',
    'Chennai',
    'Kolkata',
    'Hyderabad',
    'Pune',
    'Ahmedabad',
    'Surat',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Bhopal',
    'Patna',
    'Visakhapatnam',
    'Vadodara',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan',
    'Vasai',
    'Varanasi',
    'Srinagar',
    'Dhanbad',
    'Chandigarh',
    'Coimbatore',
    'Kochi',
    'Thiruvananthapuram'
];
